export interface QuizQuestion {
  id: string
  question: string
  options: string[]
  correctAnswer: number
  explanation: string
  difficulty: "easy" | "medium" | "hard"
  topic: string
  subtopic?: string
  eventId: string
}

export interface Quiz {
  id: string
  title: string
  description: string
  eventId: string
  questions: QuizQuestion[]
  timeLimit?: number // in minutes
  passingScore: number // percentage
  difficulty: "easy" | "medium" | "hard" | "mixed"
  subscriptionLevel: "free" | "basic" | "premium"
}

// Generate quizzes for each historical event
export const quizzes: Quiz[] = [
  {
    id: "khoi-nghia-hai-ba-trung-quiz",
    title: "Khởi nghĩa Hai Bà Trưng",
    description: "Kiểm tra kiến thức về cuộc khởi nghĩa Hai Bà Trưng",
    eventId: "khoi-nghia-hai-ba-trung",
    questions: [
      {
        id: "hbt_001",
        question: "Khởi nghĩa Hai Bà Trưng diễn ra vào năm nào?",
        options: ["Năm 39", "Năm 40", "Năm 41", "Năm 42"],
        correctAnswer: 1,
        explanation: "Khởi nghĩa Hai Bà Trưng bắt đầu vào năm 40 sau Công nguyên tại Mê Linh.",
        difficulty: "easy",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Thời gian diễn ra",
        eventId: "khoi-nghia-hai-ba-trung",
      },
      {
        id: "hbt_002",
        question: "Nguyên nhân trực tiếp dẫn đến khởi nghĩa Hai Bà Trưng là gì?",
        options: ["Thuế khóa nặng nề", "Tô Định giết chết Thi Sách", "Cướp đất của dân", "Ép dân làm lính"],
        correctAnswer: 1,
        explanation:
          "Tô Định giết chết Thi Sách (chồng của Trưng Trắc) là nguyên nhân trực tiếp khiến hai Bà Trưng khởi nghĩa.",
        difficulty: "medium",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Nguyên nhân khởi nghĩa",
        eventId: "khoi-nghia-hai-ba-trung",
      },
      {
        id: "hbt_003",
        question: "Sau khi thắng lợi, Trưng Trắc lấy hiệu là gì?",
        options: ["Trưng Vương", "Nữ Hoàng", "Trưng Nữ Vương", "Mê Linh Vương"],
        correctAnswer: 2,
        explanation: "Trưng Trắc tự lập làm Vương và lấy hiệu là Trưng Nữ Vương.",
        difficulty: "easy",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Thành lập chính quyền",
        eventId: "khoi-nghia-hai-ba-trung",
      },
      {
        id: "hbt_004",
        question: "Cuộc khởi nghĩa Hai Bà Trưng thất bại vào năm nào?",
        options: ["Năm 42", "Năm 43", "Năm 44", "Năm 45"],
        correctAnswer: 1,
        explanation: "Cuộc khởi nghĩa Hai Bà Trưng thất bại vào năm 43 sau khi bị Mã Viện đàn áp.",
        difficulty: "easy",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Kết thúc khởi nghĩa",
        eventId: "khoi-nghia-hai-ba-trung",
      },
      {
        id: "hbt_005",
        question: "Ý nghĩa quan trọng nhất của khởi nghĩa Hai Bà Trưng là gì?",
        options: [
          "Giành được độc lập lâu dài",
          "Mở đầu truyền thống đấu tranh chống ngoại xâm",
          "Thống nhất cả nước",
          "Thiết lập chế độ phong kiến",
        ],
        correctAnswer: 1,
        explanation:
          "Khởi nghĩa Hai Bà Trưng mở đầu truyền thống đấu tranh anh dũng chống ngoại xâm của dân tộc Việt Nam.",
        difficulty: "hard",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Ý nghĩa lịch sử",
        eventId: "khoi-nghia-hai-ba-trung",
      },
      {
        id: "hbt_006",
        question: "Ai là người chỉ huy quân đội nhà Hán đàn áp cuộc khởi nghĩa Hai Bà Trưng?",
        options: ["Tô Định", "Mã Viện", "Lưu Hoằng Tháo", "Lục Dận"],
        correctAnswer: 1,
        explanation: "Mã Viện là tướng nhà Hán được cử đến đàn áp cuộc khởi nghĩa Hai Bà Trưng.",
        difficulty: "medium",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Đối thủ",
        eventId: "khoi-nghia-hai-ba-trung",
      },
      {
        id: "hbt_007",
        question: "Cuộc khởi nghĩa Hai Bà Trưng đã giải phóng bao nhiêu thành trì?",
        options: ["45 thành trì", "55 thành trì", "65 thành trì", "75 thành trì"],
        correctAnswer: 2,
        explanation: "Cuộc khởi nghĩa Hai Bà Trưng đã giải phóng 65 thành trì từ Cửu Chân đến Hợp Phố.",
        difficulty: "medium",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Thành tựu",
        eventId: "khoi-nghia-hai-ba-trung",
      },
      {
        id: "hbt_008",
        question: "Hai Bà Trưng tuẫn tiết ở đâu?",
        options: ["Sông Hồng", "Sông Hát Giang", "Núi Tản Viên", "Mê Linh"],
        correctAnswer: 1,
        explanation: "Sau khi thất bại, Hai Bà Trưng đã tuẫn tiết tại sông Hát Giang.",
        difficulty: "hard",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Kết thúc khởi nghĩa",
        eventId: "khoi-nghia-hai-ba-trung",
      },
      {
        id: "hbt_009",
        question: "Đâu là một trong những nữ tướng nổi tiếng trong cuộc khởi nghĩa Hai Bà Trưng?",
        options: ["Phùng Thị Chính", "Lê Chân", "Bùi Thị Xuân", "Nguyễn Thị Minh Khai"],
        correctAnswer: 0,
        explanation: "Phùng Thị Chính là một trong những nữ tướng nổi tiếng trong cuộc khởi nghĩa Hai Bà Trưng.",
        difficulty: "hard",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Nhân vật lịch sử",
        eventId: "khoi-nghia-hai-ba-trung",
      },
      {
        id: "hbt_010",
        question: "Sau khi đàn áp cuộc khởi nghĩa Hai Bà Trưng, Mã Viện đã làm gì để đánh dấu ranh giới?",
        options: ["Xây Vạn Lý Trường Thành", "Dựng trụ đồng", "Đắp đê ngăn sông", "Xây thành lũy"],
        correctAnswer: 1,
        explanation:
          "Sau khi đàn áp cuộc khởi nghĩa Hai Bà Trưng, Mã Viện đã cho dựng trụ đồng làm ranh giới phía nam của nhà Hán.",
        difficulty: "hard",
        topic: "Khởi nghĩa Hai Bà Trưng",
        subtopic: "Hậu quả",
        eventId: "khoi-nghia-hai-ba-trung",
      },
    ],
    passingScore: 70,
    difficulty: "mixed",
    subscriptionLevel: "free",
  },
  {
    id: "khoi-nghia-ba-trieu-quiz",
    title: "Khởi nghĩa Bà Triệu",
    description: "Kiểm tra kiến thức về cuộc khởi nghĩa Bà Triệu",
    eventId: "khoi-nghia-ba-trieu",
    questions: [
      {
        id: "bt_001",
        question: "Bà Triệu tên thật là gì?",
        options: ["Triệu Thị Trinh", "Triệu Thị Nhi", "Triệu Thị Lan", "Triệu Thị Mai"],
        correctAnswer: 0,
        explanation: "Bà Triệu tên thật là Triệu Thị Trinh, sinh năm 226, mất năm 248.",
        difficulty: "easy",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Tiểu sử",
        eventId: "khoi-nghia-ba-trieu",
      },
      {
        id: "bt_002",
        question: "Khởi nghĩa Bà Triệu diễn ra ở đâu?",
        options: ["Giao Chỉ", "Cửu Chân", "Nhật Nam", "Hợp Phố"],
        correctAnswer: 1,
        explanation: "Khởi nghĩa Bà Triệu diễn ra ở Cửu Chân (nay là vùng Thanh Hóa).",
        difficulty: "medium",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Địa điểm",
        eventId: "khoi-nghia-ba-trieu",
      },
      {
        id: "bt_003",
        question: "Câu nói nổi tiếng của Bà Triệu thể hiện điều gì?",
        options: ["Lòng yêu nước", "Tinh thần bất khuất", "Ý chí độc lập", "Tất cả đều đúng"],
        correctAnswer: 3,
        explanation: "Câu nói của Bà Triệu thể hiện lòng yêu nước, tinh thần bất khuất và ý chí độc lập của dân tộc.",
        difficulty: "hard",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Tinh thần yêu nước",
        eventId: "khoi-nghia-ba-trieu",
      },
      {
        id: "bt_004",
        question: "Bà Triệu sinh vào năm nào?",
        options: ["225", "226", "227", "228"],
        correctAnswer: 1,
        explanation: "Bà Triệu sinh năm 226 và mất năm 248.",
        difficulty: "medium",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Tiểu sử",
        eventId: "khoi-nghia-ba-trieu",
      },
      {
        id: "bt_005",
        question: "Ai là người đàn áp cuộc khởi nghĩa của Bà Triệu?",
        options: ["Tô Định", "Mã Viện", "Lục Dận", "Tiền Tư Nam"],
        correctAnswer: 2,
        explanation: "Lục Dận, Thái thú Giao Châu, là người đàn áp cuộc khởi nghĩa của Bà Triệu.",
        difficulty: "medium",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Đối thủ",
        eventId: "khoi-nghia-ba-trieu",
      },
      {
        id: "bt_006",
        question: "Cuộc khởi nghĩa của Bà Triệu kéo dài trong bao lâu?",
        options: ["3 tháng", "6 tháng", "9 tháng", "1 năm"],
        correctAnswer: 1,
        explanation: "Cuộc khởi nghĩa của Bà Triệu kéo dài khoảng 6 tháng trong năm 248.",
        difficulty: "hard",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Thời gian diễn ra",
        eventId: "khoi-nghia-ba-trieu",
      },
      {
        id: "bt_007",
        question: "Bà Triệu tuẫn tiết ở đâu?",
        options: ["Núi Tùng", "Núi Nưa", "Núi Sam", "Núi Tản Viên"],
        correctAnswer: 0,
        explanation: "Sau khi thất bại, Bà Triệu đã tuẫn tiết tại núi Tùng (Thanh Hóa).",
        difficulty: "hard",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Kết thúc khởi nghĩa",
        eventId: "khoi-nghia-ba-trieu",
      },
      {
        id: "bt_008",
        question: "Anh trai của Bà Triệu tên là gì?",
        options: ["Triệu Quốc Đạt", "Triệu Quốc Tuấn", "Triệu Quang Phục", "Triệu Việt Vương"],
        correctAnswer: 0,
        explanation: "Anh trai của Bà Triệu tên là Triệu Quốc Đạt.",
        difficulty: "medium",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Nhân vật lịch sử",
        eventId: "khoi-nghia-ba-trieu",
      },
      {
        id: "bt_009",
        question: "Cuộc khởi nghĩa của Bà Triệu chống lại triều đại nào?",
        options: ["Nhà Hán", "Nhà Ngô", "Nhà Đường", "Nhà Tống"],
        correctAnswer: 1,
        explanation: "Cuộc khởi nghĩa của Bà Triệu chống lại ách đô hộ của nhà Ngô (Trung Quốc).",
        difficulty: "easy",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Đối thủ",
        eventId: "khoi-nghia-ba-trieu",
      },
      {
        id: "bt_010",
        question: "Ý nghĩa lịch sử của cuộc khởi nghĩa Bà Triệu là gì?",
        options: [
          "Giành được độc lập lâu dài",
          "Tiếp nối truyền thống đấu tranh của Hai Bà Trưng",
          "Thống nhất đất nước",
          "Thiết lập chế độ phong kiến",
        ],
        correctAnswer: 1,
        explanation:
          "Cuộc khởi nghĩa Bà Triệu có ý nghĩa tiếp nối truyền thống đấu tranh của Hai Bà Trưng, khẳng định vai trò của phụ nữ Việt Nam trong lịch sử dân tộc.",
        difficulty: "medium",
        topic: "Khởi nghĩa Bà Triệu",
        subtopic: "Ý nghĩa lịch sử",
        eventId: "khoi-nghia-ba-trieu",
      },
    ],
    passingScore: 70,
    difficulty: "mixed",
    subscriptionLevel: "free",
  },
  {
    id: "khoi-nghia-ly-bi-quiz",
    title: "Khởi nghĩa Lý Bí",
    description: "Kiểm tra kiến thức về cuộc khởi nghĩa Lý Bí và nước Vạn Xuân",
    eventId: "khoi-nghia-ly-bi",
    questions: [
      {
        id: "lb_001",
        question: "Lý Bí thành lập nước nào sau khi đánh đuổi quân Lương?",
        options: ["Đại Cồ Việt", "Vạn Xuân", "Đại Việt", "Nam Việt"],
        correctAnswer: 1,
        explanation: "Lý Bí thành lập nước Vạn Xuân năm 544 sau khi đánh đuổi quân Lương.",
        difficulty: "easy",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Thành lập nước Vạn Xuân",
        eventId: "khoi-nghia-ly-bi",
      },
      {
        id: "lb_002",
        question: "Nước Vạn Xuân tồn tại trong bao lâu?",
        options: ["58 năm", "60 năm", "65 năm", "70 năm"],
        correctAnswer: 0,
        explanation: "Nước Vạn Xuân tồn tại từ 544 đến 602, tức là 58 năm.",
        difficulty: "medium",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Thời gian tồn tại",
        eventId: "khoi-nghia-ly-bi",
      },
      {
        id: "lb_003",
        question: "Lý Bí xưng vương với niên hiệu gì?",
        options: ["Nam Việt Đế", "Vạn Xuân Đế", "Lý Nam Đế", "Tiền Lý Đế"],
        correctAnswer: 0,
        explanation: "Lý Bí xưng vương với niên hiệu là Nam Việt Đế.",
        difficulty: "medium",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Xưng vương",
        eventId: "khoi-nghia-ly-bi",
      },
      {
        id: "lb_004",
        question: "Ai là người kế vị Lý Bí sau khi ông thất bại trước quân Lương?",
        options: ["Lý Phật Tử", "Triệu Quang Phục", "Lý Thiên Bảo", "Lý Phật Tử"],
        correctAnswer: 1,
        explanation: "Triệu Quang Phục là người kế vị Lý Bí sau khi ông thất bại trước quân Lương.",
        difficulty: "medium",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Người kế vị",
        eventId: "khoi-nghia-ly-bi",
      },
      {
        id: "lb_005",
        question: "Lý Bí khởi nghĩa vào năm nào?",
        options: ["540", "541", "542", "543"],
        correctAnswer: 2,
        explanation: "Lý Bí phất cờ khởi nghĩa vào năm 542 tại Long Biên.",
        difficulty: "easy",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Thời gian diễn ra",
        eventId: "khoi-nghia-ly-bi",
      },
      {
        id: "lb_006",
        question: "Lý Bí đóng đô ở đâu sau khi thành lập nước Vạn Xuân?",
        options: ["Hoa Lư", "Long Biên", "Cổ Loa", "Thăng Long"],
        correctAnswer: 1,
        explanation: "Sau khi thành lập nước Vạn Xuân, Lý Bí đóng đô ở Long Biên.",
        difficulty: "medium",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Kinh đô",
        eventId: "khoi-nghia-ly-bi",
      },
      {
        id: "lb_007",
        question: "Lý Bí thất bại trong trận đánh nào?",
        options: ["Trận Long Biên", "Trận Chu Diên", "Trận Gia Ninh", "Trận Đại Nha"],
        correctAnswer: 1,
        explanation: "Lý Bí thất bại trong trận Chu Diên năm 546 trước quân Lương.",
        difficulty: "hard",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Thất bại",
        eventId: "khoi-nghia-ly-bi",
      },
      {
        id: "lb_008",
        question: "Ý nghĩa lịch sử của việc thành lập nước Vạn Xuân là gì?",
        options: [
          "Kết thúc hoàn toàn ách đô hộ phương Bắc",
          "Đánh dấu lần đầu tiên người Việt giành được độc lập sau hơn 500 năm Bắc thuộc",
          "Thống nhất đất nước",
          "Thiết lập chế độ phong kiến",
        ],
        correctAnswer: 1,
        explanation:
          "Việc thành lập nước Vạn Xuân đánh dấu lần đầu tiên người Việt giành được độc lập sau hơn 500 năm Bắc thuộc.",
        difficulty: "medium",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Ý nghĩa lịch sử",
        eventId: "khoi-nghia-ly-bi",
      },
      {
        id: "lb_009",
        question: "Lý Bí mất vào năm nào?",
        options: ["546", "547", "548", "549"],
        correctAnswer: 2,
        explanation: "Lý Bí mất vào năm 548, sau khi thất bại và rút về Cửu Chân.",
        difficulty: "hard",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Tiểu sử",
        eventId: "khoi-nghia-ly-bi",
      },
      {
        id: "lb_010",
        question: "Ai là tướng nhà Lương được cử đến đàn áp cuộc khởi nghĩa của Lý Bí?",
        options: ["Tiền Tư Nam", "Mã Viện", "Lục Dận", "Tô Định"],
        correctAnswer: 0,
        explanation: "Tiền Tư Nam là tướng nhà Lương được cử đến đàn áp cuộc khởi nghĩa của Lý Bí.",
        difficulty: "medium",
        topic: "Khởi nghĩa Lý Bí",
        subtopic: "Đối thủ",
        eventId: "khoi-nghia-ly-bi",
      },
    ],
    passingScore: 70,
    difficulty: "mixed",
    subscriptionLevel: "basic",
  },
  {
    id: "tran-bach-dang-938-quiz",
    title: "Trận Bạch Đằng 938",
    description: "Kiểm tra kiến thức về trận Bạch Đằng năm 938",
    eventId: "tran-bach-dang-938",
    questions: [
      {
        id: "bd938_001",
        question: "Ngô Quyền đánh bại quân nước nào trong trận Bạch Đằng 938?",
        options: ["Nhà Tùy", "Nhà Đường", "Nam Hán", "Nhà Tống"],
        correctAnswer: 2,
        explanation: "Ngô Quyền đánh bại quân Nam Hán trong trận Bạch Đằng năm 938.",
        difficulty: "easy",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Đối thủ",
        eventId: "tran-bach-dang-938",
      },
      {
        id: "bd938_002",
        question: "Chiến thuật chính của Ngô Quyền trong trận Bạch Đằng là gì?",
        options: ["Đóng cọc sông", "Phục binh", "Đánh du kích", "Bao vây"],
        correctAnswer: 0,
        explanation: "Ngô Quyền sử dụng chiến thuật đóng cọc sắt nhọn dưới sông Bạch Đằng để đánh bại quân Nam Hán.",
        difficulty: "medium",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Chiến thuật",
        eventId: "tran-bach-dang-938",
      },
      {
        id: "bd938_003",
        question: "Ý nghĩa của chiến thắng Bạch Đằng 938 là gì?",
        options: [
          "Kết thúc thời kỳ Bắc thuộc",
          "Mở đầu thời kỳ độc lập tự chủ",
          "Khẳng định ý chí độc lập của dân tộc",
          "Tất cả đều đúng",
        ],
        correctAnswer: 3,
        explanation:
          "Chiến thắng Bạch Đằng 938 có ý nghĩa to lớn: kết thúc thời kỳ Bắc thuộc, mở đầu thời kỳ độc lập và khẳng định ý chí độc lập của dân tộc.",
        difficulty: "hard",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Ý nghĩa lịch sử",
        eventId: "tran-bach-dang-938",
      },
      {
        id: "bd938_004",
        question: "Ai là chỉ huy quân Nam Hán trong trận Bạch Đằng 938?",
        options: ["Lưu Cung", "Lưu Hoằng Tháo", "Lưu Ẩn", "Lưu Nghĩa"],
        correctAnswer: 1,
        explanation:
          "Lưu Hoằng Tháo, con trai của Lưu Cung - vua Nam Hán, là người chỉ huy quân Nam Hán trong trận Bạch Đằng 938.",
        difficulty: "medium",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Đối thủ",
        eventId: "tran-bach-dang-938",
      },
      {
        id: "bd938_005",
        question: "Sau chiến thắng Bạch Đằng, Ngô Quyền đóng đô ở đâu?",
        options: ["Hoa Lư", "Long Biên", "Cổ Loa", "Thăng Long"],
        correctAnswer: 2,
        explanation: "Sau chiến thắng Bạch Đằng, Ngô Quyền lên ngôi vua và đóng đô ở Cổ Loa.",
        difficulty: "medium",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Hậu quả",
        eventId: "tran-bach-dang-938",
      },
      {
        id: "bd938_006",
        question: "Trước khi đánh bại quân Nam Hán, Ngô Quyền đã đánh bại ai?",
        options: ["Kiều Công Tiễn", "Dương Đình Nghệ", "Lý Bí", "Triệu Quang Phục"],
        correctAnswer: 0,
        explanation:
          "Trước khi đánh bại quân Nam Hán, Ngô Quyền đã đánh bại Kiều Công Tiễn - người đã giết chết Dương Đình Nghệ và cầu cứu quân Nam Hán.",
        difficulty: "medium",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Bối cảnh",
        eventId: "tran-bach-dang-938",
      },
      {
        id: "bd938_007",
        question: "Ngô Quyền sinh vào năm nào?",
        options: ["895", "896", "897", "898"],
        correctAnswer: 2,
        explanation: "Ngô Quyền sinh năm 897 và mất năm 944.",
        difficulty: "hard",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Tiểu sử",
        eventId: "tran-bach-dang-938",
      },
      {
        id: "bd938_008",
        question: "Trận Bạch Đằng 938 diễn ra ở đâu?",
        options: ["Sông Hồng", "Sông Bạch Đằng", "Sông Cầu", "Sông Đuống"],
        correctAnswer: 1,
        explanation: "Trận Bạch Đằng 938 diễn ra trên sông Bạch Đằng, nay thuộc địa phận Quảng Ninh và Hải Phòng.",
        difficulty: "easy",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Địa điểm",
        eventId: "tran-bach-dang-938",
      },
      {
        id: "bd938_009",
        question: "Thời kỳ Bắc thuộc kéo dài bao lâu trước khi kết thúc bởi chiến thắng Bạch Đằng 938?",
        options: ["Hơn 500 năm", "Hơn 700 năm", "Hơn 1000 năm", "Hơn 1200 năm"],
        correctAnswer: 2,
        explanation:
          "Thời kỳ Bắc thuộc kéo dài hơn 1000 năm (từ 179 TCN đến 938) trước khi kết thúc bởi chiến thắng Bạch Đằng 938.",
        difficulty: "medium",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Bối cảnh",
        eventId: "tran-bach-dang-938",
      },
      {
        id: "bd938_010",
        question: "Ngô Quyền mất vào năm nào?",
        options: ["942", "943", "944", "945"],
        correctAnswer: 2,
        explanation: "Ngô Quyền mất vào năm 944, sau 6 năm trị vì.",
        difficulty: "medium",
        topic: "Trận Bạch Đằng 938",
        subtopic: "Tiểu sử",
        eventId: "tran-bach-dang-938",
      },
    ],
    passingScore: 70,
    difficulty: "mixed",
    subscriptionLevel: "free",
  },
  {
    id: "chien-thang-chi-lang-1427-quiz",
    title: "Chiến thắng Chi Lăng - Xương Giang 1427",
    description: "Kiểm tra kiến thức về chiến thắng Chi Lăng - Xương Giang 1427",
    eventId: "chien-thang-chi-lang-1427",
    questions: [
      {
        id: "cl_001",
        question: "Ai là người lãnh đạo nghĩa quân Lam Sơn trong chiến thắng Chi Lăng - Xương Giang?",
        options: ["Lê Lợi", "Nguyễn Trãi", "Trần Nguyên Hãn", "Lê Lai"],
        correctAnswer: 0,
        explanation: "Lê Lợi là người lãnh đạo nghĩa quân Lam Sơn trong chiến thắng Chi Lăng - Xương Giang.",
        difficulty: "easy",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Lãnh đạo",
        eventId: "chien-thang-chi-lang-1427",
      },
      {
        id: "cl_002",
        question: "Chiến thắng Chi Lăng - Xương Giang diễn ra vào năm nào?",
        options: ["1426", "1427", "1428", "1429"],
        correctAnswer: 1,
        explanation: "Chiến thắng Chi Lăng - Xương Giang diễn ra vào cuối năm 1427.",
        difficulty: "easy",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Thời gian diễn ra",
        eventId: "chien-thang-chi-lang-1427",
      },
      {
        id: "cl_003",
        question: "Ai là tướng nhà Minh bị giết tại ải Chi Lăng?",
        options: ["Vương Thông", "Liễu Thăng", "Mộc Thạnh", "Hoàng Phúc"],
        correctAnswer: 1,
        explanation: "Liễu Thăng là tướng nhà Minh bị giết tại ải Chi Lăng vào ngày 20/10/1427.",
        difficulty: "medium",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Đối thủ",
        eventId: "chien-thang-chi-lang-1427",
      },
      {
        id: "cl_004",
        question: "Chiến thắng Chi Lăng - Xương Giang kết thúc thời kỳ nào trong lịch sử Việt Nam?",
        options: [
          "Thời kỳ Bắc thuộc lần thứ nhất",
          "Thời kỳ Bắc thuộc lần thứ hai",
          "Thời kỳ Bắc thuộc lần thứ ba",
          "Thời kỳ Bắc thuộc lần thứ tư",
        ],
        correctAnswer: 3,
        explanation: "Chiến thắng Chi Lăng - Xương Giang kết thúc thời kỳ Bắc thuộc lần thứ tư (1407-1427).",
        difficulty: "medium",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Ý nghĩa lịch sử",
        eventId: "chien-thang-chi-lang-1427",
      },
      {
        id: "cl_005",
        question: "Ai là mưu sĩ giúp Lê Lợi hoạch định chiến lược trong cuộc kháng chiến chống Minh?",
        options: ["Nguyễn Trãi", "Trần Nguyên Hãn", "Lê Lai", "Phạm Văn Xảo"],
        correctAnswer: 0,
        explanation: "Nguyễn Trãi là mưu sĩ giúp Lê Lợi hoạch định chiến lược trong cuộc kháng chiến chống Minh.",
        difficulty: "easy",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Nhân vật lịch sử",
        eventId: "chien-thang-chi-lang-1427",
      },
      {
        id: "cl_006",
        question: "Chiến lược của Nguyễn Trãi trong cuộc kháng chiến chống Minh là gì?",
        options: [
          "Đánh nhanh thắng nhanh",
          "Lấy đại nghĩa thắng hung tàn, lấy chí nhân thay cường bạo",
          "Tiên phát chế nhân",
          "Vườn không nhà trống",
        ],
        correctAnswer: 1,
        explanation:
          "Chiến lược của Nguyễn Trãi trong cuộc kháng chiến chống Minh là 'Lấy đại nghĩa thắng hung tàn, lấy chí nhân thay cường bạo'.",
        difficulty: "medium",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Chiến lược",
        eventId: "chien-thang-chi-lang-1427",
      },
      {
        id: "cl_007",
        question: "Sau chiến thắng Chi Lăng - Xương Giang, ai đã đầu hàng và rút quân khỏi Đại Việt?",
        options: ["Liễu Thăng", "Mộc Thạnh", "Vương Thông", "Hoàng Phúc"],
        correctAnswer: 2,
        explanation: "Sau chiến thắng Chi Lăng - Xương Giang, Vương Thông đã đầu hàng và rút quân khỏi Đại Việt.",
        difficulty: "medium",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Hậu quả",
        eventId: "chien-thang-chi-lang-1427",
      },
      {
        id: "cl_008",
        question: "Cuộc khởi nghĩa Lam Sơn bắt đầu vào năm nào?",
        options: ["1416", "1417", "1418", "1419"],
        correctAnswer: 2,
        explanation: "Cuộc khởi nghĩa Lam Sơn do Lê Lợi lãnh đạo bắt đầu vào năm 1418.",
        difficulty: "medium",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Bối cảnh",
        eventId: "chien-thang-chi-lang-1427",
      },
      {
        id: "cl_009",
        question: "Sau khi giành độc lập, Lê Lợi lên ngôi vua với niên hiệu gì?",
        options: ["Lê Thái Tổ", "Lê Thái Tông", "Lê Thánh Tông", "Lê Hiến Tông"],
        correctAnswer: 0,
        explanation:
          "Sau khi giành độc lập, Lê Lợi lên ngôi vua với niên hiệu Lê Thái Tổ, sáng lập triều đại nhà Hậu Lê.",
        difficulty: "medium",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Hậu quả",
        eventId: "chien-thang-chi-lang-1427",
      },
      {
        id: "cl_010",
        question: "Nhà Minh đô hộ Đại Việt từ năm nào đến năm nào?",
        options: ["1400-1427", "1406-1427", "1407-1427", "1408-1427"],
        correctAnswer: 2,
        explanation: "Nhà Minh đô hộ Đại Việt từ năm 1407 đến năm 1427.",
        difficulty: "hard",
        topic: "Chiến thắng Chi Lăng - Xương Giang 1427",
        subtopic: "Bối cảnh",
        eventId: "chien-thang-chi-lang-1427",
      },
    ],
    passingScore: 70,
    difficulty: "mixed",
    subscriptionLevel: "basic",
  },
  {
    id: "chien-thang-dong-da-1789-quiz",
    title: "Chiến thắng Đống Đa 1789",
    description: "Kiểm tra kiến thức về chiến thắng Đống Đa 1789",
    eventId: "chien-thang-dong-da-1789",
    questions: [
      {
        id: "dd_001",
        question: "Ai là người lãnh đạo quân Tây Sơn trong chiến thắng Đống Đa?",
        options: ["Nguyễn Huệ", "Nguyễn Nhạc", "Nguyễn Lữ", "Nguyễn Ánh"],
        correctAnswer: 0,
        explanation: "Nguyễn Huệ (Quang Trung) là người lãnh đạo quân Tây Sơn trong chiến thắng Đống Đa.",
        difficulty: "easy",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Lãnh đạo",
        eventId: "chien-thang-dong-da-1789",
      },
      {
        id: "dd_002",
        question: "Chiến thắng Đống Đa diễn ra vào dịp Tết năm nào?",
        options: ["Tết Kỷ Dậu (1789)", "Tết Canh Tuất (1790)", "Tết Tân Hợi (1791)", "Tết Nhâm Tý (1792)"],
        correctAnswer: 0,
        explanation: "Chiến thắng Đống Đa diễn ra vào dịp Tết Kỷ Dậu (1789).",
        difficulty: "easy",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Thời gian diễn ra",
        eventId: "chien-thang-dong-da-1789",
      },
      {
        id: "dd_003",
        question: "Quân Tây Sơn đánh bại quân đội nước nào trong chiến thắng Đống Đa?",
        options: ["Nhà Minh", "Nhà Thanh", "Nhà Nguyễn", "Nhà Lê"],
        correctAnswer: 1,
        explanation: "Quân Tây Sơn đánh bại quân đội nhà Thanh trong chiến thắng Đống Đa.",
        difficulty: "easy",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Đối thủ",
        eventId: "chien-thang-dong-da-1789",
      },
      {
        id: "dd_004",
        question: "Ai là người chỉ huy quân Thanh trong chiến dịch xâm lược Đại Việt?",
        options: ["Tôn Sĩ Nghị", "Phúc Khang An", "Lê Chiêu Thống", "Nguyễn Ánh"],
        correctAnswer: 0,
        explanation: "Tôn Sĩ Nghị là người chỉ huy quân Thanh trong chiến dịch xâm lược Đại Việt.",
        difficulty: "medium",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Đối thủ",
        eventId: "chien-thang-dong-da-1789",
      },
      {
        id: "dd_005",
        question: "Nguyễn Huệ lên ngôi hoàng đế với niên hiệu gì trước khi ra quân đánh giặc Thanh?",
        options: ["Quang Trung", "Thái Đức", "Cảnh Thịnh", "Gia Long"],
        correctAnswer: 0,
        explanation: "Nguyễn Huệ lên ngôi hoàng đế với niên hiệu Quang Trung trước khi ra quân đánh giặc Thanh.",
        difficulty: "medium",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Lãnh đạo",
        eventId: "chien-thang-dong-da-1789",
      },
      {
        id: "dd_006",
        question: "Quân Tây Sơn xuất phát từ đâu để ra Bắc đánh giặc Thanh?",
        options: ["Phú Xuân", "Nghệ An", "Thanh Hóa", "Thăng Long"],
        correctAnswer: 1,
        explanation: "Quân Tây Sơn xuất phát từ Nghệ An để ra Bắc đánh giặc Thanh.",
        difficulty: "medium",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Chiến dịch",
        eventId: "chien-thang-dong-da-1789",
      },
      {
        id: "dd_007",
        question: "Quân Thanh xâm lược Đại Việt với bao nhiêu quân?",
        options: ["19 vạn", "29 vạn", "39 vạn", "49 vạn"],
        correctAnswer: 1,
        explanation: "Quân Thanh xâm lược Đại Việt với 29 vạn quân.",
        difficulty: "hard",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Đối thủ",
        eventId: "chien-thang-dong-da-1789",
      },
      {
        id: "dd_008",
        question: "Chiến thắng Đống Đa diễn ra trong bao nhiêu ngày?",
        options: ["3 ngày", "5 ngày", "7 ngày", "10 ngày"],
        correctAnswer: 1,
        explanation: "Chiến thắng Đống Đa diễn ra trong vòng 5 ngày, từ ngày 30/12/1788 đến ngày 5/1/1789 (âm lịch).",
        difficulty: "medium",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Thời gian diễn ra",
        eventId: "chien-thang-dong-da-1789",
      },
      {
        id: "dd_009",
        question: "Ai là vua cuối cùng của nhà Lê đã cầu cứu nhà Thanh?",
        options: ["Lê Hiển Tông", "Lê Chiêu Thống", "Lê Duy Kỳ", "Lê Duy Phường"],
        correctAnswer: 1,
        explanation: "Lê Chiêu Thống là vua cuối cùng của nhà Lê đã cầu cứu nhà Thanh để chống lại nhà Tây Sơn.",
        difficulty: "medium",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Bối cảnh",
        eventId: "chien-thang-dong-da-1789",
      },
      {
        id: "dd_010",
        question: "Nguyễn Huệ mất vào năm nào?",
        options: ["1790", "1791", "1792", "1793"],
        correctAnswer: 2,
        explanation: "Nguyễn Huệ (Quang Trung) mất vào năm 1792, chỉ sau 3 năm trị vì.",
        difficulty: "medium",
        topic: "Chiến thắng Đống Đa 1789",
        subtopic: "Tiểu sử",
        eventId: "chien-thang-dong-da-1789",
      },
    ],
    passingScore: 70,
    difficulty: "mixed",
    subscriptionLevel: "basic",
  },
  {
    id: "dien-bien-phu-1954-quiz",
    title: "Chiến dịch Điện Biên Phủ 1954",
    description: "Kiểm tra kiến thức về chiến dịch Điện Biên Phủ 1954",
    eventId: "dien-bien-phu-1954",
    questions: [
      {
        id: "dbp_001",
        question: "Chiến dịch Điện Biên Phủ diễn ra khi nào?",
        options: ["13/3/1954 - 7/5/1954", "13/3/1954 - 17/5/1954", "13/2/1954 - 7/5/1954", "13/3/1953 - 7/5/1953"],
        correctAnswer: 0,
        explanation: "Chiến dịch Điện Biên Phủ diễn ra từ ngày 13/3/1954 đến ngày 7/5/1954.",
        difficulty: "easy",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Thời gian diễn ra",
        eventId: "dien-bien-phu-1954",
      },
      {
        id: "dbp_002",
        question: "Ai là tổng chỉ huy chiến dịch Điện Biên Phủ?",
        options: ["Hồ Chí Minh", "Võ Nguyên Giáp", "Hoàng Văn Thái", "Văn Tiến Dũng"],
        correctAnswer: 1,
        explanation: "Đại tướng Võ Nguyên Giáp là tổng chỉ huy chiến dịch Điện Biên Phủ.",
        difficulty: "easy",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Lãnh đạo",
        eventId: "dien-bien-phu-1954",
      },
      {
        id: "dbp_003",
        question: "Ai là chỉ huy tập đoàn cứ điểm Điện Biên Phủ của Pháp?",
        options: ["Henri Navarre", "Christian de Castries", "René Cogny", "Jean de Lattre de Tassigny"],
        correctAnswer: 1,
        explanation: "Đại tá Christian de Castries là chỉ huy tập đoàn cứ điểm Điện Biên Phủ của Pháp.",
        difficulty: "medium",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Đối thủ",
        eventId: "dien-bien-phu-1954",
      },
      {
        id: "dbp_004",
        question: "Kế hoạch Navarre nhằm mục đích gì?",
        options: [
          "Giành lại thế chủ động trong cuộc chiến",
          "Tiêu diệt chủ lực quân đội Việt Nam",
          "Ngăn chặn quân đội Việt Nam tiến vào Lào",
          "Tất cả đều đúng",
        ],
        correctAnswer: 3,
        explanation:
          "Kế hoạch Navarre nhằm giành lại thế chủ động trong cuộc chiến, tiêu diệt chủ lực quân đội Việt Nam và ngăn chặn quân đội Việt Nam tiến vào Lào.",
        difficulty: "medium",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Bối cảnh",
        eventId: "dien-bien-phu-1954",
      },
      {
        id: "dbp_005",
        question: "Chiến dịch Điện Biên Phủ bắt đầu với trận đánh vào cứ điểm nào?",
        options: ["Him Lam", "Độc Lập", "Bản Kéo", "A1"],
        correctAnswer: 0,
        explanation: "Chiến dịch Điện Biên Phủ bắt đầu với trận đánh vào cứ điểm Him Lam vào ngày 13/3/1954.",
        difficulty: "medium",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Chiến dịch",
        eventId: "dien-bien-phu-1954",
      },
      {
        id: "dbp_006",
        question: "Quân đội Pháp nhảy dù xuống Điện Biên Phủ vào ngày nào?",
        options: ["20/10/1953", "20/11/1953", "20/12/1953", "20/1/1954"],
        correctAnswer: 1,
        explanation:
          "Quân đội Pháp nhảy dù xuống Điện Biên Phủ vào ngày 20/11/1953, bắt đầu xây dựng tập đoàn cứ điểm.",
        difficulty: "hard",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Bối cảnh",
        eventId: "dien-bien-phu-1954",
      },
      {
        id: "dbp_007",
        question: "Hiệp định Genève được ký kết vào ngày nào?",
        options: ["21/6/1954", "21/7/1954", "21/8/1954", "21/9/1954"],
        correctAnswer: 1,
        explanation:
          "Hiệp định Genève được ký kết vào ngày 21/7/1954, chấm dứt chiến tranh và công nhận độc lập, chủ quyền của Việt Nam.",
        difficulty: "medium",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Hậu quả",
        eventId: "dien-bien-phu-1954",
      },
      {
        id: "dbp_008",
        question: "Quân đội Việt Nam đã tiêu diệt và bắt sống bao nhiêu quân Pháp tại Điện Biên Phủ?",
        options: ["10.200 quân", "12.200 quân", "14.200 quân", "16.200 quân"],
        correctAnswer: 3,
        explanation: "Quân đội Việt Nam đã tiêu diệt và bắt sống toàn bộ quân Pháp tại Điện Biên Phủ (16.200 quân).",
        difficulty: "hard",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Kết quả",
        eventId: "dien-bien-phu-1954",
      },
      {
        id: "dbp_009",
        question: "Cứ điểm cuối cùng của Pháp tại Điện Biên Phủ bị tiêu diệt là cứ điểm nào?",
        options: ["Him Lam", "Độc Lập", "A1", "Hầm chỉ huy của De Castries"],
        correctAnswer: 2,
        explanation: "Cứ điểm A1 là cứ điểm cuối cùng của Pháp tại Điện Biên Phủ bị tiêu diệt.",
        difficulty: "hard",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Chiến dịch",
        eventId: "dien-bien-phu-1954",
      },
      {
        id: "dbp_010",
        question: "Chiến thắng Điện Biên Phủ có ý nghĩa gì đối với phong trào giải phóng dân tộc trên thế giới?",
        options: [
          "Không có ý nghĩa gì đặc biệt",
          "Chỉ có ý nghĩa đối với Việt Nam",
          "Mở ra cao trào giải phóng dân tộc trên toàn thế giới",
          "Làm suy yếu các nước đế quốc",
        ],
        correctAnswer: 2,
        explanation:
          "Chiến thắng Điện Biên Phủ mở ra cao trào giải phóng dân tộc trên toàn thế giới, góp phần làm sụp đổ hệ thống thuộc địa của chủ nghĩa đế quốc.",
        difficulty: "medium",
        topic: "Chiến dịch Điện Biên Phủ 1954",
        subtopic: "Ý nghĩa lịch sử",
        eventId: "dien-bien-phu-1954",
      },
    ],
    passingScore: 70,
    difficulty: "mixed",
    subscriptionLevel: "premium",
  },
  {
    id: "giai-phong-mien-nam-1975-quiz",
    title: "Chiến dịch Hồ Chí Minh 1975",
    description: "Kiểm tra kiến thức về chiến dịch Hồ Chí Minh 1975",
    eventId: "giai-phong-mien-nam-1975",
    questions: [
      {
        id: "hcm_001",
        question: "Chiến dịch Hồ Chí Minh diễn ra từ ngày nào đến ngày nào?",
        options: ["26/4/1975 - 30/4/1975", "26/3/1975 - 30/4/1975", "26/4/1975 - 30/5/1975", "26/3/1975 - 30/5/1975"],
        correctAnswer: 0,
        explanation: "Chiến dịch Hồ Chí Minh diễn ra từ ngày 26/4/1975 đến ngày 30/4/1975.",
        difficulty: "easy",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Thời gian diễn ra",
        eventId: "giai-phong-mien-nam-1975",
      },
      {
        id: "hcm_002",
        question: "Ai là tổng tư lệnh chiến dịch Hồ Chí Minh?",
        options: ["Võ Nguyên Giáp", "Văn Tiến Dũng", "Lê Đức Thọ", "Nguyễn Chí Thanh"],
        correctAnswer: 1,
        explanation: "Đại tướng Văn Tiến Dũng là tổng tư lệnh chiến dịch Hồ Chí Minh.",
        difficulty: "medium",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Lãnh đạo",
        eventId: "giai-phong-mien-nam-1975",
      },
      {
        id: "hcm_003",
        question: "Ai là tổng thống cuối cùng của Việt Nam Cộng hòa?",
        options: ["Nguyễn Văn Thiệu", "Trần Văn Hương", "Dương Văn Minh", "Nguyễn Cao Kỳ"],
        correctAnswer: 2,
        explanation:
          "Dương Văn Minh là tổng thống cuối cùng của Việt Nam Cộng hòa, người tuyên bố đầu hàng vô điều kiện vào ngày 30/4/1975.",
        difficulty: "easy",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Đối thủ",
        eventId: "giai-phong-mien-nam-1975",
      },
      {
        id: "hcm_004",
        question: "Trước chiến dịch Hồ Chí Minh, quân giải phóng đã giành thắng lợi trong những chiến dịch nào?",
        options: [
          "Chiến dịch Tây Nguyên và Huế-Đà Nẵng",
          "Chiến dịch Điện Biên Phủ và Tây Nguyên",
          "Chiến dịch Huế-Đà Nẵng và Quảng Trị",
          "Chiến dịch Tây Nguyên và Quảng Trị",
        ],
        correctAnswer: 0,
        explanation:
          "Trước chiến dịch Hồ Chí Minh, quân giải phóng đã giành thắng lợi trong chiến dịch Tây Nguyên và Huế-Đà Nẵng vào tháng 3/1975.",
        difficulty: "medium",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Bối cảnh",
        eventId: "giai-phong-mien-nam-1975",
      },
      {
        id: "hcm_005",
        question: "Nguyễn Văn Thiệu từ chức Tổng thống Việt Nam Cộng hòa vào ngày nào?",
        options: ["20/4/1975", "21/4/1975", "22/4/1975", "23/4/1975"],
        correctAnswer: 1,
        explanation: "Nguyễn Văn Thiệu từ chức Tổng thống Việt Nam Cộng hòa vào ngày 21/4/1975.",
        difficulty: "medium",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Bối cảnh",
        eventId: "giai-phong-mien-nam-1975",
      },
      {
        id: "hcm_006",
        question: "Xe tăng quân giải phóng tiến vào Dinh Độc Lập vào thời gian nào?",
        options: ["30/4/1975, 10:30", "30/4/1975, 10:45", "30/4/1975, 11:00", "30/4/1975, 11:15"],
        correctAnswer: 1,
        explanation: "Xe tăng quân giải phóng tiến vào Dinh Độc Lập vào lúc 10:45 ngày 30/4/1975.",
        difficulty: "hard",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Chiến dịch",
        eventId: "giai-phong-mien-nam-1975",
      },
      {
        id: "hcm_007",
        question: "Dương Văn Minh tuyên bố đầu hàng vô điều kiện vào thời gian nào?",
        options: ["30/4/1975, 11:00", "30/4/1975, 11:15", "30/4/1975, 11:30", "30/4/1975, 11:45"],
        correctAnswer: 2,
        explanation: "Dương Văn Minh tuyên bố đầu hàng vô điều kiện vào lúc 11:30 ngày 30/4/1975.",
        difficulty: "hard",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Chiến dịch",
        eventId: "giai-phong-mien-nam-1975",
      },
      {
        id: "hcm_008",
        question: "Chiến thắng 30/4/1975 kết thúc bao nhiêu năm chiến tranh giải phóng dân tộc?",
        options: ["20 năm", "25 năm", "30 năm", "35 năm"],
        correctAnswer: 2,
        explanation: "Chiến thắng 30/4/1975 kết thúc 30 năm chiến tranh giải phóng dân tộc (1945-1975).",
        difficulty: "medium",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Ý nghĩa lịch sử",
        eventId: "giai-phong-mien-nam-1975",
      },
      {
        id: "hcm_009",
        question: "Hiệp định Paris được ký kết vào năm nào?",
        options: ["1971", "1972", "1973", "1974"],
        correctAnswer: 2,
        explanation: "Hiệp định Paris được ký kết vào năm 1973, nhưng không được thực thi nghiêm túc.",
        difficulty: "medium",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Bối cảnh",
        eventId: "giai-phong-mien-nam-1975",
      },
      {
        id: "hcm_010",
        question: "Ý nghĩa quan trọng nhất của chiến thắng 30/4/1975 là gì?",
        options: [
          "Kết thúc chiến tranh",
          "Thống nhất đất nước",
          "Mở ra thời kỳ hòa bình, độc lập, thống nhất",
          "Tất cả đều đúng",
        ],
        correctAnswer: 3,
        explanation:
          "Chiến thắng 30/4/1975 có ý nghĩa to lớn: kết thúc chiến tranh, thống nhất đất nước và mở ra thời kỳ hòa bình, độc lập, thống nhất.",
        difficulty: "easy",
        topic: "Chiến dịch Hồ Chí Minh 1975",
        subtopic: "Ý nghĩa lịch sử",
        eventId: "giai-phong-mien-nam-1975",
      },
    ],
    passingScore: 70,
    difficulty: "mixed",
    subscriptionLevel: "premium",
  },
]

export function getQuizById(id: string): Quiz | undefined {
  return quizzes.find((quiz) => quiz.id === id)
}

export function getQuizzesByEventId(eventId: string): Quiz[] {
  return quizzes.filter((quiz) => quiz.eventId === eventId)
}

export function getQuizzesBySubscriptionLevel(level: "free" | "basic" | "premium"): Quiz[] {
  if (level === "premium") {
    return quizzes
  } else if (level === "basic") {
    return quizzes.filter((quiz) => quiz.subscriptionLevel === "free" || quiz.subscriptionLevel === "basic")
  } else {
    return quizzes.filter((quiz) => quiz.subscriptionLevel === "free")
  }
}

export function getQuizzesByDifficulty(difficulty: "easy" | "medium" | "hard" | "mixed"): Quiz[] {
  return quizzes.filter((quiz) => quiz.difficulty === difficulty)
}

export function searchQuizzes(query: string): Quiz[] {
  const lowercaseQuery = query.toLowerCase()
  return quizzes.filter(
    (quiz) =>
      quiz.title.toLowerCase().includes(lowercaseQuery) ||
      quiz.description.toLowerCase().includes(lowercaseQuery) ||
      quiz.questions.some((question) => question.question.toLowerCase().includes(lowercaseQuery)),
  )
}
